username: "universitparysaclay_jemali_achraf"
password: "wOAk18B95k"
locations: 
  - { name: "Paris", lat: 48.8566, lon: 2.3522 }
  - { name: "Lyon", lat: 45.7640, lon: 4.8357 }
  - { name: "London", lat: 51.5074, lon: -0.1278 }
  - { name: "New York", lat: 40.7128, lon: -74.0060 }
  - { name: "Tokyo", lat: 35.6895, lon: 139.6917 }
  - { name: "Sydney", lat: -33.8688, lon: 151.2093 }
  - { name: "Moscow", lat: 55.7558, lon: 37.6173 }
  - { name: "Beijing", lat: 39.9042, lon: 116.4074 }
  - { name: "Dubai", lat: 25.276987, lon: 55.296249 }
  - { name: "São Paulo", lat: -23.5505, lon: -46.6333 }
parameters: "wind_speed_10m:ms,wind_dir_10m:d,wind_gusts_10m_1h:ms,wind_gusts_10m_24h:ms,t_2m:C,t_max_2m_24h:C,t_min_2m_24h:C,msl_pressure:hPa,precip_1h:mm,precip_24h:mm"
output_format: "json"
interval: 30  # Fetch data every 1/2 minutes
